name: Xcode - Build and Analyze

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-11

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.0'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          xcodebuild build-for-testing -project GameOfLife.xcodeproj -scheme GameOfLife
      - name: Test
        run: |
          xcodebuild test -project GameOfLife.xcodeproj -scheme GameOfLife | xcpretty && exit ${PIPESTATUS[0]}
